name = "roll-dorado-casino-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.gr"
HMAC_KEY = "0a2b527099030a6a13f0c3625619237db550dd0363ead98ab3e23a46f9cf6ed8"
COOKIE_NAME = "auk"
PLAY_PATH = "discover"
BUTTON_ID = "p7e13d29635c197292ac7e52501cd9de3"
GATE_SALT = "ecd97c965da0dbab"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "4ypv"
CTA_SELECTOR = ".play-button"
